# Generated by Django 6.0.7 on 2026-08-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=20)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
